#!C:\Users\home\Documents\GitHub\ExportAnalysis\Scripts\python.exe
# EASY-INSTALL-SCRIPT: 'numba==0.52.0','numba'
__requires__ = 'numba==0.52.0'
__import__('pkg_resources').run_script('numba==0.52.0', 'numba')
